[env]
platform = espressif32
framework = arduino
build_flags = -std=gnu++2a
build_unflags = -std=gnu++11
monitor_speed = 115200
lib_deps = symlink://../..

[env:esp32c3]
board = lolin_c3_mini

[env:esp32dev]
board = esp32dev

[env:esp32cam]
board = esp32cam
