#pragma once

#include "../Bitmap.h"
#include "../Clip.h"

namespace mrm {
namespace ui {
namespace glyph {

inline constexpr auto kBluetoothBitmap = mrm::bitmap<7, 9>(R"(
    ...#...
    ...###.
    #..#..#
    .#####.
    ...#...
    .#####.
    #..#..#
    ...###.
    ...#...
)");
inline constexpr mrm::gfx::Icon kBluetooth = kBluetoothBitmap.icon();

inline constexpr auto kBatteryFrameBitmap = mrm::bitmap<14, 7>(R"(
    ############..
    #..........#..
    #..........###
    #..........###
    #..........###
    #..........#..
    ############..
)");
inline constexpr mrm::gfx::Icon kBatteryFrame = kBatteryFrameBitmap.icon();

inline constexpr auto kCheckBitmap = mrm::bitmap<7, 6>(R"(
    ......#
    .....#.
    ....#..
    #...#..
    .#.#...
    ..#....
)");
inline constexpr mrm::gfx::Icon kCheck = kCheckBitmap.icon();

// Quadros do sinal subindo. A origem de cada quadro é o centro da base dos arcos.
inline constexpr auto kWifiSmall0Bitmap = mrm::bitmap<13, 8>(R"(
    .............
    .............
    .............
    .............
    .............
    ......#......
    .....###.....
    ......#......
)");
inline constexpr mrm::gfx::Icon kWifiSmall0 = kWifiSmall0Bitmap.icon();
inline constexpr auto kWifiSmall1Bitmap = mrm::bitmap<13, 8>(R"(
    .............
    .............
    .............
    .............
    .....###.....
    ....#.#.#....
    ....#####....
    ......#......
)");
inline constexpr mrm::gfx::Icon kWifiSmall1 = kWifiSmall1Bitmap.icon();
inline constexpr auto kWifiSmall2Bitmap = mrm::bitmap<13, 8>(R"(
    .............
    .............
    .....###.....
    ...##...##...
    ...#.###.#...
    ..#.#.#.#.#..
    ....#####....
    ......#......
)");
inline constexpr mrm::gfx::Icon kWifiSmall2 = kWifiSmall2Bitmap.icon();
inline constexpr auto kWifiSmall3Bitmap = mrm::bitmap<13, 8>(R"(
    ....#####....
    ...#.....#...
    ..#..###..#..
    .#.##...##.#.
    #..#.###.#..#
    #.#.#.#.#.#.#
    ....#####....
    ......#......
)");
inline constexpr mrm::gfx::Icon kWifiSmall3 = kWifiSmall3Bitmap.icon();
inline constexpr mrm::Frame kWifiSmallFrames[] = {
    {&kWifiSmall0, -6, -6, 250},
    {&kWifiSmall1, -6, -6, 250},
    {&kWifiSmall2, -6, -6, 250},
    {&kWifiSmall3, -6, -6, 250},
};
inline constexpr mrm::Clip kWifiSmall{kWifiSmallFrames, 4};

// Quadros do sinal subindo. A origem de cada quadro é o centro da base dos arcos.
inline constexpr auto kWifiLarge0Bitmap = mrm::bitmap<23, 13>(R"(
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    ...........#...........
    ..........###..........
    ...........#...........
)");
inline constexpr mrm::gfx::Icon kWifiLarge0 = kWifiLarge0Bitmap.icon();
inline constexpr auto kWifiLarge1Bitmap = mrm::bitmap<23, 13>(R"(
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    .......................
    ..........###..........
    ........##...##........
    ........#.....#........
    .......#...#...#.......
    ..........###..........
    ...........#...........
)");
inline constexpr mrm::gfx::Icon kWifiLarge1 = kWifiLarge1Bitmap.icon();
inline constexpr auto kWifiLarge2Bitmap = mrm::bitmap<23, 13>(R"(
    .......................
    .......................
    .......................
    .........#####.........
    .......##.....##.......
    ......#.........#......
    .....#...........#.....
    ....#.....###.....#....
    ....#...##...##...#....
    ...#....#.....#....#...
    .......#...#...#.......
    ..........###..........
    ...........#...........
)");
inline constexpr mrm::gfx::Icon kWifiLarge2 = kWifiLarge2Bitmap.icon();
inline constexpr auto kWifiLarge3Bitmap = mrm::bitmap<23, 13>(R"(
    ........#######........
    ......##.......##......
    .....#...........#.....
    ...##....#####....##...
    ...#...##.....##...#...
    ..#...#.........#...#..
    .#...#...........#...#.
    .#..#.....###.....#..#.
    #...#...##...##...#...#
    #..#....#.....#....#..#
    .......#...#...#.......
    ..........###..........
    ...........#...........
)");
inline constexpr mrm::gfx::Icon kWifiLarge3 = kWifiLarge3Bitmap.icon();
inline constexpr mrm::Frame kWifiLargeFrames[] = {
    {&kWifiLarge0, -11, -11, 300},
    {&kWifiLarge1, -11, -11, 300},
    {&kWifiLarge2, -11, -11, 300},
    {&kWifiLarge3, -11, -11, 300},
};
inline constexpr mrm::Clip kWifiLarge{kWifiLargeFrames, 4};

} // namespace glyph
} // namespace ui
} // namespace mrm
